- name: ASM export playbook
  hosts: bigips
  gather_facts: False

  vars:
    state: "present"
    policy_name1: asm-l7-policy
    asm_policy_template: "/var/tmp/ansible/templates/asm-template-1.xml"
    asm_policy_name: new_asm_policy

  environment: "{{ bigip_env }}"

  tasks:
    - name: Export ASM policy
      bigip_command:
        commands: "save asm policy {{ asm_policy_name }} xml-file /var/tmp/export-{{ asm_policy_name }}.xml"
      delegate_to: localhost

    - name: Fetch ASM policy
      fetch:
        src: /var/tmp/{{ asm_policy_name }}.xml
        dest: ../templates/
        flat: yes
