- name: Git upload
  hosts: localhost
  gather_facts: False

  vars_prompt:
    - name: git_username
      prompt: "Username"
      default: "migara"
      private: no
    - name: git_password
      prompt: "Password"
      default: "{{ git_token }}"  
      private: yes
    - name: git_owner
      prompt: "Git Owner"
      default: "migara"
      private: no
    - name: git_repo
      prompt: "Repo Name"
      default: "ASM"  
      private: no
    - name: git_branch
      prompt: "Git Branch"
      default: "dev"
      private: no
    - name: commit_msg
      prompt: "Commit message"
      default: "commit"
      private: no
    - name: file_name
      prompt: "File"
      default: "template-1.xml"  
      private: no

  tasks:
  - import_tasks: ../files/git.yml
    